"""Immutable COS publisher v1 states.

PACKAGE_READY != PUBLISH_APPROVED != PUBLISHED != CATALOG_DISCOVERABLE.
"""

from __future__ import annotations

from enum import Enum


class PublicationState(str, Enum):
    NOT_AUTHORIZED = "NOT_AUTHORIZED"
    LOCAL_PACKAGE_NOT_READY = "LOCAL_PACKAGE_NOT_READY"
    PRECHECK_FAILED = "PRECHECK_FAILED"
    UPLOADING = "UPLOADING"
    VERIFYING = "VERIFYING"
    PUBLISHED = "PUBLISHED"
    ALREADY_PUBLISHED_IDENTICAL = "ALREADY_PUBLISHED_IDENTICAL"
    IMMUTABLE_RELEASE_CONFLICT = "IMMUTABLE_RELEASE_CONFLICT"
    REMOTE_VERIFY_FAILED = "REMOTE_VERIFY_FAILED"
    COS_ERROR = "COS_ERROR"


class ReasonCode(str, Enum):
    PUBLISH_NOT_AUTHORIZED = "PUBLISH_NOT_AUTHORIZED"
    LOCAL_PACKAGE_NOT_READY = "LOCAL_PACKAGE_NOT_READY"
    INVALID_WALL_ID = "INVALID_WALL_ID"
    INVALID_RELEASE_ID = "INVALID_RELEASE_ID"
    WALL_ID_MISMATCH = "WALL_ID_MISMATCH"
    RELEASE_ID_MISMATCH = "RELEASE_ID_MISMATCH"
    DEVELOPMENT_PACKAGE_NOT_PUBLISHABLE = "DEVELOPMENT_PACKAGE_NOT_PUBLISHABLE"
    PACKAGE_DIR_MISSING = "PACKAGE_DIR_MISSING"
    STORE_REQUIRED = "STORE_REQUIRED"
    IMMUTABLE_RELEASE_CONFLICT = "IMMUTABLE_RELEASE_CONFLICT"
    REMOTE_ASSET_VERIFY_FAILED = "REMOTE_ASSET_VERIFY_FAILED"
    REMOTE_MANIFEST_VERIFY_FAILED = "REMOTE_MANIFEST_VERIFY_FAILED"
    REMOTE_MANIFEST_IDENTITY_MISMATCH = "REMOTE_MANIFEST_IDENTITY_MISMATCH"
    INCOMPLETE_PUBLISHED_RELEASE = "INCOMPLETE_PUBLISHED_RELEASE"
    COS_ERROR = "COS_ERROR"
    CATALOG_KEY_FORBIDDEN = "CATALOG_KEY_FORBIDDEN"


TERMINAL_SUCCESS = frozenset(
    {
        PublicationState.PUBLISHED,
        PublicationState.ALREADY_PUBLISHED_IDENTICAL,
    }
)
