"""Local Gate 5A / 5C route ingestion. Not a Stage 5 package. Not publishable."""

from __future__ import annotations

SCHEMA_VERSION = "gate5a.ingested.route.1"
INGESTED_KIND = "canonical_ingested_route"
FIXTURE_SCHEMA = "gate5c.development.route.fixture.1"
FIXTURE_KIND = "development_validation_route_fixture"
BUNDLE_SCHEMA = "gate5c.development.route.bundle.1"
JOB_SCHEMA = "route_ingestion.job.1"
FREEZE_SCHEMA = "route_ingestion.input_freeze.1"
COORDINATE_FRAME = "WallMetricMeters"
PROVENANCE = "IDENTITY_SUPPORTED"
XYZ_FRAME_ID = "wall_local_metres"

MIN_POLYLINE_POINTS = 2
MAX_ABS_METRES = 1000.0
DUMMY_ORIGIN = (0.0, 0.0, 0.0)

REASON_NO_ROUTES = "ROUTE_INPUTS_NOT_FOUND"
REASON_UNEXPECTED_NAMESPACE = "ROUTE_NAMESPACE_UNEXPECTED_FILE"
REASON_PARSE_FAILED = "ROUTE_DXF_PARSE_FAILED"
REASON_GEOMETRY_INVALID = "ROUTE_GEOMETRY_INVALID"
REASON_METADATA_INVALID = "ROUTE_METADATA_INVALID"
REASON_COORDINATE_FRAME = "ROUTE_COORDINATE_FRAME_NOT_ESTABLISHED"
REASON_BIND_FAILED = "ROUTE_BASELINE_BIND_FAILED"
REASON_PROVENANCE = "ROUTE_PROVENANCE_MISMATCH"
REASON_INPUT_MUTATED = "ROUTE_INPUT_MUTATED"
REASON_LOCALIZATION = "ROUTE_LOCALIZATION_PACKAGE_NOT_READY"
REASON_NOT_CLOUDCOMPARE = "ROUTE_NOT_CLOUDCOMPARE_DXF"

GATE_STOP = "STOP"
GATE_READY_FOR_FIELD_IPHONE = "READY_FOR_FIELD_IPHONE_TEST"
