"""Production Localization Package v1 local schema constants.

Not a Wall Package, route package, or published Cloud release.
"""

from __future__ import annotations

from enum import Enum

PACKAGE_SCHEMA = "cragpal.localization-package.v1"
CLOUD_MANIFEST_SCHEMA = "cragpal.wall-manifest.v1"

ENVIRONMENT_PRODUCTION = "production"
ENVIRONMENT_DEVELOPMENT_TEST = "development_test"
ENVIRONMENTS = frozenset({ENVIRONMENT_PRODUCTION, ENVIRONMENT_DEVELOPMENT_TEST})

STATE_CONSTRUCTED = "CONSTRUCTED"
STATE_NOT_PACKAGE_READY = "NOT_PACKAGE_READY"
STATE_PACKAGE_READY = "PACKAGE_READY"

TYPE_DESCRIPTORS = "reference_descriptors_rvs1"
TYPE_LANDMARKS = "reference_landmarks_json"
# Proposed Cloud semantic type. Manifest `type` is an extensible string.
# Current iOS CloudStage3AssetSemantics does NOT consume this type.
TYPE_S_WALL_COLMAP = "s_wall_colmap_json"

SIM3_STATUS_VALIDATED = "VALIDATED"

COLMAP_IDENTITY_PROVEN = "COLMAP_SOURCE_IDENTITY_PROVEN"
POSITIONING_FIXED = "POSITIONING_QUALITY_FIXED"


class ReasonCode(str, Enum):
    INVALID_PACKAGE_SCHEMA = "INVALID_PACKAGE_SCHEMA"
    INVALID_WALL_ID = "INVALID_WALL_ID"
    INVALID_RELEASE_ID = "INVALID_RELEASE_ID"
    INVALID_ENVIRONMENT = "INVALID_ENVIRONMENT"
    WALL_ID_MISMATCH = "WALL_ID_MISMATCH"
    RELEASE_ID_MISMATCH = "RELEASE_ID_MISMATCH"
    MISSING_REQUIRED_ASSET = "MISSING_REQUIRED_ASSET"
    ASSET_TYPE_MISMATCH = "ASSET_TYPE_MISMATCH"
    ASSET_HASH_MISMATCH = "ASSET_HASH_MISMATCH"
    ASSET_BYTES_MISMATCH = "ASSET_BYTES_MISMATCH"
    DESCRIPTORS_REQUIRED = "DESCRIPTORS_REQUIRED"
    LANDMARKS_REQUIRED = "LANDMARKS_REQUIRED"
    METRIC_SIM3_REQUIRED = "METRIC_SIM3_REQUIRED"
    SIM3_NOT_VALIDATED = "SIM3_NOT_VALIDATED"
    SIM3_INVALID_GEOMETRY = "SIM3_INVALID_GEOMETRY"
    SIM3_WALL_BUILD_RUN_MISMATCH = "SIM3_WALL_BUILD_RUN_MISMATCH"
    SIM3_MODEL_FINGERPRINT_MISMATCH = "SIM3_MODEL_FINGERPRINT_MISMATCH"
    POSITIONING_QUALITY_NOT_PASS = "POSITIONING_QUALITY_NOT_PASS"
    HEIGHT_GATE_NOT_PASS = "HEIGHT_GATE_NOT_PASS"
    COLMAP_SOURCE_IDENTITY_NOT_PROVEN = "COLMAP_SOURCE_IDENTITY_NOT_PROVEN"
    DEVELOPMENT_FIXTURE_NOT_PRODUCTION = "DEVELOPMENT_FIXTURE_NOT_PRODUCTION"
    NOT_A_WALL_PACKAGE_FLAG = "NOT_A_WALL_PACKAGE_FLAG"
    STAGE3_REFERENCE_MAP_BINDING_NOT_PROVEN = "STAGE3_REFERENCE_MAP_BINDING_NOT_PROVEN"
    STAGE3_REFERENCE_MAP_BINDING_MISMATCH = "STAGE3_REFERENCE_MAP_BINDING_MISMATCH"
    FREEZE_WALL_BUILD_RUN_MISMATCH = "FREEZE_WALL_BUILD_RUN_MISMATCH"
    FREEZE_MODEL_FINGERPRINT_MISMATCH = "FREEZE_MODEL_FINGERPRINT_MISMATCH"
    ROUTES_NOT_AUTHORIZED = "ROUTES_NOT_AUTHORIZED"
    DECLARED_STATE_MISMATCH = "DECLARED_STATE_MISMATCH"
    MISSING_EVIDENCE = "MISSING_EVIDENCE"
    CLOUD_MANIFEST_INVALID = "CLOUD_MANIFEST_INVALID"
    COS_LAYOUT_FORBIDDEN = "COS_LAYOUT_FORBIDDEN"


REQUIRED_ASSET_TYPES = (TYPE_DESCRIPTORS, TYPE_LANDMARKS, TYPE_S_WALL_COLMAP)

EVIDENCE_SELECTION = "stage2_input_selection.json"
EVIDENCE_POSITIONING = "positioning_quality.json"
EVIDENCE_HEIGHT = "height_vertical_datum.json"
EVIDENCE_COLMAP_IDENTITY = "colmap_source_identity.json"
EVIDENCE_FREEZE = "freeze.json"

FORBIDDEN_ROUTE_NAMES = frozenset(
    {
        "routes.json",
        "route_test_01",
        "route_test_01.json",
    }
)
