"""Machine-readable states, stages, and reason codes for Phase 1."""

from __future__ import annotations

from enum import Enum


class Stage(str, Enum):
    DISCOVERY = "DISCOVERY"
    PREFLIGHT = "PREFLIGHT"
    INGEST = "INGEST"
    QUALIFY = "QUALIFY"
    STAGE2_SELECTION = "STAGE2_SELECTION"
    HEIGHT_VERTICAL_DATUM = "HEIGHT_VERTICAL_DATUM"
    POSITIONING_QUALITY = "POSITIONING_QUALITY"
    RECONSTRUCTION = "RECONSTRUCTION"
    METRIC_REGISTRATION = "METRIC_REGISTRATION"
    REGISTER = "REGISTER"
    REFERENCE_MATCH = "REFERENCE_MATCH"
    PNP = "PNP"
    REFERENCE_MAP = "REFERENCE_MAP"
    ROUTE_COORDINATE_REGISTRATION = "ROUTE_COORDINATE_REGISTRATION"
    ROUTE_PACKAGE_BUILD = "ROUTE_PACKAGE_BUILD"


class StageStatus(str, Enum):
    AUTO_PASS = "AUTO_PASS"
    AUTO_FAIL = "AUTO_FAIL"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    DEVELOPMENT_GATE_REVIEW_REQUIRED = "DEVELOPMENT_GATE_REVIEW_REQUIRED"
    BLOCKED = "BLOCKED"
    SKIPPED = "SKIPPED"


class RunTerminalStatus(str, Enum):
    AUTO_FAIL = "AUTO_FAIL"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    DEVELOPMENT_GATE_REVIEW_REQUIRED = "DEVELOPMENT_GATE_REVIEW_REQUIRED"


class AutomationReached(str, Enum):
    NONE = "NONE"
    DISCOVERY_COMPLETE = "DISCOVERY_COMPLETE"
    PREFLIGHT_COMPLETE = "PREFLIGHT_COMPLETE"
    INGEST_COMPLETE = "INGEST_COMPLETE"
    QUALIFICATION_COMPLETE = "QUALIFICATION_COMPLETE"
    STAGE2_SELECTION_COMPLETE = "STAGE2_SELECTION_COMPLETE"
    HEIGHT_DATUM_COMPLETE = "HEIGHT_DATUM_COMPLETE"
    POSITIONING_QUALITY_COMPLETE = "POSITIONING_QUALITY_COMPLETE"
    RECONSTRUCTION_COMPLETE = "RECONSTRUCTION_COMPLETE"
    METRIC_REGISTRATION_COMPLETE = "METRIC_REGISTRATION_COMPLETE"
    REFERENCE_MAP_COMPLETE = "REFERENCE_MAP_COMPLETE"
    ROUTE_INGESTION_COMPLETE = "ROUTE_INGESTION_COMPLETE"
    ROUTE_REGISTRATION_COMPLETE = "ROUTE_REGISTRATION_COMPLETE"
    PACKAGE_COMPLETE = "PACKAGE_COMPLETE"


class ReasonCode(str, Enum):
    INPUT_MUTATED_DURING_RUN = "INPUT_MUTATED_DURING_RUN"
    MISSING_REQUIRED_SOURCE_IMAGES = "MISSING_REQUIRED_SOURCE_IMAGES"
    ZERO_BYTE_RECOGNIZED_INPUT = "ZERO_BYTE_RECOGNIZED_INPUT"
    CORRUPT_DXF = "CORRUPT_DXF"
    INGEST_FAILED = "INGEST_FAILED"
    QUALIFY_FAILED = "QUALIFY_FAILED"
    GENERIC_STAGE2_NOT_APPROVED = "GENERIC_STAGE2_NOT_APPROVED"
    STAGE2_SELECTION_NOT_AUTO_PASS = "STAGE2_SELECTION_NOT_AUTO_PASS"
    RECONSTRUCTION_FAILED = "RECONSTRUCTION_FAILED"
    METRIC_REGISTRATION_FAILED = "METRIC_REGISTRATION_FAILED"
    DXF_COORDINATE_PROVENANCE_METHOD_NOT_APPROVED = "DXF_COORDINATE_PROVENANCE_METHOD_NOT_APPROVED"
    ROUTE_PACKAGE_NOT_AUTHORIZED = "ROUTE_PACKAGE_NOT_AUTHORIZED"
    PHASE1_STAGE_NOT_IN_ALLOWLIST = "PHASE1_STAGE_NOT_IN_ALLOWLIST"
    INVALID_WALL_ID = "INVALID_WALL_ID"
    MISSING_WALL_DIRECTORY = "MISSING_WALL_DIRECTORY"
    WALL_PATH_NOT_DIRECTORY = "WALL_PATH_NOT_DIRECTORY"
    UNSAFE_WALL_PATH = "UNSAFE_WALL_PATH"
    UPSTREAM_STAGE_NOT_COMPLETE = "UPSTREAM_STAGE_NOT_COMPLETE"
    IGNORED_UNKNOWN_FILE = "IGNORED_UNKNOWN_FILE"
    MULTIPLE_CAPTURE_CANDIDATES = "MULTIPLE_CAPTURE_CANDIDATES"
    MULTIPLE_MRK_CANDIDATES = "MULTIPLE_MRK_CANDIDATES"
    MULTIPLE_METADATA_CANDIDATES = "MULTIPLE_METADATA_CANDIDATES"
    MULTIPLE_MODEL_CANDIDATES = "MULTIPLE_MODEL_CANDIDATES"


PHASE1_EXECUTABLE_STAGES = frozenset(
    {
        Stage.DISCOVERY,
        Stage.PREFLIGHT,
        Stage.INGEST,
        Stage.QUALIFY,
    }
)

PRODUCTION_EXECUTABLE_STAGES = frozenset(
    {
        Stage.DISCOVERY,
        Stage.PREFLIGHT,
        Stage.INGEST,
        Stage.QUALIFY,
        Stage.STAGE2_SELECTION,
        Stage.HEIGHT_VERTICAL_DATUM,
        Stage.POSITIONING_QUALITY,
        Stage.RECONSTRUCTION,
        Stage.METRIC_REGISTRATION,
    }
)

PRODUCTION_STAGE_SEQUENCE = (
    Stage.DISCOVERY,
    Stage.PREFLIGHT,
    Stage.INGEST,
    Stage.QUALIFY,
    Stage.STAGE2_SELECTION,
    Stage.HEIGHT_VERTICAL_DATUM,
    Stage.POSITIONING_QUALITY,
    Stage.RECONSTRUCTION,
    Stage.METRIC_REGISTRATION,
)

PHASE1_FORBIDDEN_STAGES = frozenset(
    {
        Stage.REGISTER,
        Stage.REFERENCE_MATCH,
        Stage.PNP,
        Stage.REFERENCE_MAP,
        Stage.ROUTE_COORDINATE_REGISTRATION,
        Stage.ROUTE_PACKAGE_BUILD,
    }
)

INVENTORY_WARNING_CODES = frozenset(
    {
        ReasonCode.MULTIPLE_CAPTURE_CANDIDATES,
        ReasonCode.MULTIPLE_MRK_CANDIDATES,
        ReasonCode.MULTIPLE_METADATA_CANDIDATES,
        ReasonCode.MULTIPLE_MODEL_CANDIDATES,
        ReasonCode.IGNORED_UNKNOWN_FILE,
        ReasonCode.ZERO_BYTE_RECOGNIZED_INPUT,
    }
)

# Production Phase 1 never triggers HUMAN_REVIEW_REQUIRED.
# The enum exists for the state machine; only unit tests may construct it.
HUMAN_REVIEW_PRODUCTION_TRIGGERS: frozenset[str] = frozenset()
