"""Selection-state semantics. These four statuses are not interchangeable."""

from __future__ import annotations

from enum import Enum

SCHEMA_VERSION = "stage2_input_selection.1"
OUTPUT_FRAME = "WallLocal"
WALLMETRICMETERS_PROVENANCE = "NOT_CLAIMED"
APPROVED_SRS = "EPSG:32650"
ORIGIN_SANITY_MAX_OFFSET_M = 250.0

FROZEN_JIULONGFENG_ASSOCIATION_RULE = "FROZEN_JIULONGFENG_ASSOCIATION_RULE"
GENERIC_MRK_ASSOCIATION_RULE = "GENERIC_MRK_ASSOCIATION_RULE"
PROPOSED_MODEL_TREE_RULE = "PROPOSED_GENERIC_RULE_REQUIRING_VALIDATION"


class SelectionStatus(str, Enum):
    AUTO_PASS = "AUTO_PASS"
    AUTO_FAIL = "AUTO_FAIL"
    HUMAN_REVIEW_REQUIRED = "HUMAN_REVIEW_REQUIRED"
    DEVELOPMENT_GATE_REVIEW_REQUIRED = "DEVELOPMENT_GATE_REVIEW_REQUIRED"


class ReasonCode(str, Enum):
    UNIQUE_LEGAL_SOURCE_SET = "UNIQUE_LEGAL_SOURCE_SET"
    ZERO_COMPATIBLE_PRIMARY_CAPTURE = "ZERO_COMPATIBLE_PRIMARY_CAPTURE"
    MULTIPLE_SELECTABLE_CAPTURE_GROUPS = "MULTIPLE_SELECTABLE_CAPTURE_GROUPS"
    MRK_MISSING = "MRK_MISSING"
    MRK_AMBIGUOUS = "MRK_AMBIGUOUS"
    MRK_NON_SAME_PARENT_INSUFFICIENT_EVIDENCE = "MRK_NON_SAME_PARENT_INSUFFICIENT_EVIDENCE"
    MODEL_SPATIAL_METADATA_MISSING = "MODEL_SPATIAL_METADATA_MISSING"
    MODEL_SPATIAL_METADATA_MALFORMED = "MODEL_SPATIAL_METADATA_MALFORMED"
    MODEL_SPATIAL_METADATA_AMBIGUOUS = "MODEL_SPATIAL_METADATA_AMBIGUOUS"
    MODEL_METADATA_ASSOCIATION_RULE_INSUFFICIENT = "MODEL_METADATA_ASSOCIATION_RULE_INSUFFICIENT"
    SRS_NOT_EPSG_32650 = "SRS_NOT_EPSG_32650"
    SRSORIGIN_MALFORMED = "SRSORIGIN_MALFORMED"
    PLY_MISSING = "PLY_MISSING"
    PLY_AMBIGUOUS_NO_APPROVED_RULE = "PLY_AMBIGUOUS_NO_APPROVED_RULE"
    MODEL_GEOMETRY_METADATA_ASSOCIATION_UNPROVEN = "MODEL_GEOMETRY_METADATA_ASSOCIATION_UNPROVEN"
    SELECTED_IMAGES_NOT_SINGLE_DIRECTORY = "SELECTED_IMAGES_NOT_SINGLE_DIRECTORY"


def worst_status(statuses: list[SelectionStatus]) -> SelectionStatus:
    rank = {
        SelectionStatus.AUTO_FAIL: 0,
        SelectionStatus.DEVELOPMENT_GATE_REVIEW_REQUIRED: 1,
        SelectionStatus.HUMAN_REVIEW_REQUIRED: 2,
        SelectionStatus.AUTO_PASS: 3,
    }
    if not statuses:
        return SelectionStatus.DEVELOPMENT_GATE_REVIEW_REQUIRED
    return min(statuses, key=lambda item: rank[item])
