"""Catalog promotion v1 states.

PUBLISHED != PROMOTION_APPROVED != CATALOG_DISCOVERABLE.
"""

from __future__ import annotations

from enum import Enum


class PromotionState(str, Enum):
    PROMOTION_NOT_AUTHORIZED = "PROMOTION_NOT_AUTHORIZED"
    REMOTE_RELEASE_INVALID = "REMOTE_RELEASE_INVALID"
    CATALOG_INVALID = "CATALOG_INVALID"
    CATALOG_NAME_CONFLICT = "CATALOG_NAME_CONFLICT"
    CATALOG_RELEASE_REGRESSION = "CATALOG_RELEASE_REGRESSION"
    CATALOG_CONCURRENT_MODIFICATION = "CATALOG_CONCURRENT_MODIFICATION"
    CATALOG_VERIFY_FAILED = "CATALOG_VERIFY_FAILED"
    CATALOG_DISCOVERABLE = "CATALOG_DISCOVERABLE"
    ALREADY_CATALOG_DISCOVERABLE = "ALREADY_CATALOG_DISCOVERABLE"
    COS_ERROR = "COS_ERROR"


class ReasonCode(str, Enum):
    PROMOTION_NOT_AUTHORIZED = "PROMOTION_NOT_AUTHORIZED"
    INVALID_WALL_ID = "INVALID_WALL_ID"
    INVALID_RELEASE_ID = "INVALID_RELEASE_ID"
    INVALID_DISPLAY_NAME = "INVALID_DISPLAY_NAME"
    STORE_REQUIRED = "STORE_REQUIRED"
    REMOTE_MANIFEST_MISSING = "REMOTE_MANIFEST_MISSING"
    REMOTE_MANIFEST_INVALID = "REMOTE_MANIFEST_INVALID"
    REMOTE_MANIFEST_WALL_ID_MISMATCH = "REMOTE_MANIFEST_WALL_ID_MISMATCH"
    REMOTE_MANIFEST_RELEASE_ID_MISMATCH = "REMOTE_MANIFEST_RELEASE_ID_MISMATCH"
    REMOTE_DESCRIPTORS_MISSING = "REMOTE_DESCRIPTORS_MISSING"
    REMOTE_LANDMARKS_MISSING = "REMOTE_LANDMARKS_MISSING"
    REMOTE_SIM3_MISSING = "REMOTE_SIM3_MISSING"
    REMOTE_DUPLICATE_SEMANTIC_TYPE = "REMOTE_DUPLICATE_SEMANTIC_TYPE"
    REMOTE_ASSET_NOT_REQUIRED = "REMOTE_ASSET_NOT_REQUIRED"
    REMOTE_ASSET_MISSING = "REMOTE_ASSET_MISSING"
    REMOTE_ASSET_BYTES_MISMATCH = "REMOTE_ASSET_BYTES_MISMATCH"
    REMOTE_ASSET_SHA_MISMATCH = "REMOTE_ASSET_SHA_MISMATCH"
    REMOTE_ASSET_VERIFY_FAILED = "REMOTE_ASSET_VERIFY_FAILED"
    CATALOG_INVALID = "CATALOG_INVALID"
    CATALOG_SCHEMA_UNSUPPORTED = "CATALOG_SCHEMA_UNSUPPORTED"
    CATALOG_NAME_CONFLICT = "CATALOG_NAME_CONFLICT"
    CATALOG_RELEASE_REGRESSION = "CATALOG_RELEASE_REGRESSION"
    CATALOG_CONCURRENT_MODIFICATION = "CATALOG_CONCURRENT_MODIFICATION"
    CATALOG_VERIFY_FAILED = "CATALOG_VERIFY_FAILED"
    CATALOG_ETAG_MISSING = "CATALOG_ETAG_MISSING"
    COS_ERROR = "COS_ERROR"


TERMINAL_SUCCESS = frozenset(
    {
        PromotionState.CATALOG_DISCOVERABLE,
        PromotionState.ALREADY_CATALOG_DISCOVERABLE,
    }
)
