"""Catalog promotion states.

PUBLISHED != PROMOTION_APPROVED != PROMOTION_RECORD_CREATED.
PROMOTION_RECORD_CREATED != CATALOG_DISCOVERABLE until backend projection.
"""

from __future__ import annotations

from enum import Enum


class PromotionState(str, Enum):
    PROMOTION_NOT_AUTHORIZED = "PROMOTION_NOT_AUTHORIZED"
    REMOTE_RELEASE_INVALID = "REMOTE_RELEASE_INVALID"
    PROMOTION_NAME_CONFLICT = "PROMOTION_NAME_CONFLICT"
    PROMOTION_RECORD_INVALID = "PROMOTION_RECORD_INVALID"
    IMMUTABLE_PROMOTION_CONFLICT = "IMMUTABLE_PROMOTION_CONFLICT"
    PROMOTION_VERIFY_FAILED = "PROMOTION_VERIFY_FAILED"
    PROMOTION_RECORD_CREATED = "PROMOTION_RECORD_CREATED"
    ALREADY_PROMOTED_IDENTICAL = "ALREADY_PROMOTED_IDENTICAL"
    COS_ERROR = "COS_ERROR"


class ReasonCode(str, Enum):
    PROMOTION_NOT_AUTHORIZED = "PROMOTION_NOT_AUTHORIZED"
    INVALID_WALL_ID = "INVALID_WALL_ID"
    INVALID_RELEASE_ID = "INVALID_RELEASE_ID"
    INVALID_DISPLAY_NAME = "INVALID_DISPLAY_NAME"
    STORE_REQUIRED = "STORE_REQUIRED"
    REMOTE_MANIFEST_MISSING = "REMOTE_MANIFEST_MISSING"
    REMOTE_MANIFEST_INVALID = "REMOTE_MANIFEST_INVALID"
    REMOTE_MANIFEST_WALL_ID_MISMATCH = "REMOTE_MANIFEST_WALL_ID_MISMATCH"
    REMOTE_MANIFEST_RELEASE_ID_MISMATCH = "REMOTE_MANIFEST_RELEASE_ID_MISMATCH"
    REMOTE_DESCRIPTORS_MISSING = "REMOTE_DESCRIPTORS_MISSING"
    REMOTE_LANDMARKS_MISSING = "REMOTE_LANDMARKS_MISSING"
    REMOTE_SIM3_MISSING = "REMOTE_SIM3_MISSING"
    REMOTE_DUPLICATE_SEMANTIC_TYPE = "REMOTE_DUPLICATE_SEMANTIC_TYPE"
    REMOTE_ASSET_NOT_REQUIRED = "REMOTE_ASSET_NOT_REQUIRED"
    REMOTE_ASSET_MISSING = "REMOTE_ASSET_MISSING"
    REMOTE_ASSET_BYTES_MISMATCH = "REMOTE_ASSET_BYTES_MISMATCH"
    REMOTE_ASSET_SHA_MISMATCH = "REMOTE_ASSET_SHA_MISMATCH"
    PROMOTION_NAME_CONFLICT = "PROMOTION_NAME_CONFLICT"
    PROMOTION_RECORD_INVALID = "PROMOTION_RECORD_INVALID"
    PROMOTION_SCHEMA_UNSUPPORTED = "PROMOTION_SCHEMA_UNSUPPORTED"
    PROMOTION_IDENTITY_CONFLICT = "PROMOTION_IDENTITY_CONFLICT"
    IMMUTABLE_PROMOTION_CONFLICT = "IMMUTABLE_PROMOTION_CONFLICT"
    PROMOTION_VERIFY_FAILED = "PROMOTION_VERIFY_FAILED"
    COS_ERROR = "COS_ERROR"


TERMINAL_SUCCESS = frozenset(
    {
        PromotionState.PROMOTION_RECORD_CREATED,
        PromotionState.ALREADY_PROMOTED_IDENTICAL,
    }
)
